### ISSUE TITLE
Question about isolation of databases

### ISSUE THREAD

**Issue by suadev** [devmentors/DNC-DShop.Services.Discounts#1]
Hi,

My question is about the line below. Discount and Customer are two seperate databases, right?

On the line below, Discount service is accessing the Customer service's db directly.

In microservices architecture,  this is not right way. Discount service need to make a http call to customer service. 

what do you think about it?

 var customer = await _customersRepository.GetAsync(discount.CustomerId);

**Comment by GooRiOn** [comment]
You're not correct. Notice that discounts service subscribes to `CustomerCreted` event. In its event handler it creates a local version of `Customer` (just with Id and Email) which is then stored inside discounts DB. The line you pasted is nothing more but a call to local DB with local copy of a customer.

Here's an event handler that synchronizes data: https://github.com/devmentors/DNC-DShop.Services.Discounts/blob/master/src/DShop.Services.Discounts/Handlers/Customers/CustomerCreatedHandler.cs

**Comment by suadev** [comment]
@GooRiOn sorry my bad.  

I missed that point. 

Even if i don't like the pattern that a service keeps a local copy of another service's data, it's ok with microservices architecture.

**Comment by spetz** [comment]
Such data duplication reduces the temporal coupling. Events are one way of achieving the asynchronous integration. Imagine the following scenario: you want to fetch the order details data (some read-model). Either, your Orders Service is being dependent on the Products Service (and each time you fetch the Order DTO from DB you have to internally call Products Service to get products, which might be temporarily offline or so), or you keep the data in your own DB, which improves the overall service resiliency. Not to mention that Product aggregate has a totally different meaning when talking about the Orders (where it's just a historical data within the Order Item).

**Comment by suadev** [comment]
@spetz Is this pattern comes from DDD approach or it'is your own decision, i wanted to ask firstly.

Your explanation is absolutely make sense. But, i think this pattern also bring with a data syncronization challange. Let me explain.

Discount service is up and running but something went wrong while creating the customer on its own database. So, CustomerCreatedEvent message is not exist in the queue anymore right?  What would we do in this scenario?  I guess, rabbitmq can configure to handle this kind of situations. For example;  We can say, Do not delete the message from the queue untill the consumer say i finished with it.  What do you think?﻿

**Comment by spetz** [comment]
@suadev you're correct, and the data synchronization issues might happen. At first, you should always have the message bus cluster up and running, meaning that all of the queues will be there and there's a message dump (onto disks, db etc). If anything goes wrong, the whole broker should be restarted and load all of the messages (so nothing should be missing). You can easily configure it with RabbitMQ (durable queues + persistent messages, however, this one comes affects overall performance).

**Comment by nick-cromwell** [comment]
I wanted to follow up with 2 additional questions.

The first is regarding data synchronization. Given a scenario where one microservice, M1, has been running for some extended period of time, and all of the messages it is subscribed to have been ack'd. The rabbit queue would be clear and entries would be stored in M1's database. Then, some time in the future, a second microservice, M2, comes online that subscribes to the same event types as M1. There is a data inconsistency. M1 will likely have a larger dataset than M2.

If an event or command is put into the queue which both M1 and M2 are subscribed to, how should M2 handle an event relating to an entry that is not in its database? Should it fall back to try reading the missing entry from M1?

Secondly, if this is the preferred approach. Why, in `Discounts.Handlers.Orders.OrderCompletedHandler`, do we make a request to the order service instead of subscribing to an `OrderCreated` event and then in the `OrderCompleted` handler, fetch the order from the Discount Service's database? Isn't this introducing temporal coupling?
